name: project2_social_media
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.3
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  email_validator: ^2.0.1
  eva_icons_flutter: ^3.0.2
  firebase_auth: ^3.1.2
  firebase_core: ^1.7.0
  firebase_storage: ^10.0.4
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0
  flutter_sticky_header: ^0.6.0
  font_awesome_flutter: ^9.1.0
  google_sign_in: ^5.1.1
  image_picker: ^0.8.4+2
  like_button: ^2.0.3
  page_transition: ^2.0.4
  provider: ^6.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
    - family: Monteserrat
      fonts:
        - asset: assets/fonts/Monteserat.ttf
